config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  resources :routines
  devise_for :users
  root 'routines#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  validates :description, presence: true
  validates :power_level, presence: true, inclusion: { in: 0..10 }

  has_many :exercise_routines
  has_many :routines, through: :exercise_routines 
end

app/models/exercise_routine.rb
class ExerciseRoutine < ApplicationRecord
  belongs_to :exercise
  belongs_to :routine
end

app/models/routine.rb
class Routine < ApplicationRecord
  has_many :exercise_routines, dependent: :delete_all
  has_many :exercises, through: :exercise_routines  
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    routines_path
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]

  def index
    @exercises = Exercise.all
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)

    return render :new, status: :unprocessable_entity unless @exercise.save
    redirect_to @exercise, notice: "Exercise was successfully created."
  end

  def edit
  end

  def update
    return render :edit, status: :unprocessable_entity unless @exercise.update(exercise_params)
    redirect_to @exercise, notice: "Exercise was successfully updated."
  end

  def destroy
    @exercise.destroy

    redirect_to exercises_url, notice: "Exercise was successfully destroyed."
  end

  private
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      params.require(:exercise).permit(:name, :description, :power_level)
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: %i[ index ]

  def index
    @routines = Routine.all
  end

  def show
  end

  def new
    @routine = Routine.new
  end
  
  def create
    @routine = Routine.new(routine_params)
    
    return render :edit, status: :unprocessable_entity unless @routine.save
    redirect_to @routine, notice: "Routine was successfully created."    
  end
  
  def edit
  end

  def update
    return render :edit, status: :unprocessable_entity unless @routine.update(routine_params)
    redirect_to @routine, notice: "Routine was successfully updated."
  end

  def destroy
    @routine.destroy

    redirect_to routines_path, notice: "Routine was successfully destroyed."
  end

  private
  def set_routine
    @routine = Routine.find(params[:id])
  end
  
  def routine_params
    params.require(:routine).permit(:name, exercise_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
</div>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, size: '20x5' %>
  </div>
  <div>
    <%= form.label :power_level %><br>
    <%= form.number_field(:power_level, in: 0..10) %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Show this exercise", @exercise %> |
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/index.html.erb
<h1>Exercises</h1>

<div id="exercises">
  <table>
    <thead>
      <tr>
        <th><strong>Name</strong></th>  
      </tr>
    </thead>
    <tbody>      
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.name %></td>
          <td><%= link_to "show exercise", exercise %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New exercise", new_exercise_path %>  
</div>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/show.html.erb
<div id="exercise">
  <table>
    <thead>
      <tr>
        <th><strong>Name</strong></th>
        <th><strong>Description</strong></th>
        <th><strong>Power Level</strong></th>  
      </tr>
    </thead>
    <tbody>      
      <tr>
        <td><%= @exercise.name %></td>
        <td><%= @exercise.description %></td>
        <td><%= @exercise.power_level %></td>
      </tr>
    </tbody>
  </table>
</div>

<div>
  <%= link_to "Edit this exercise", edit_exercise_path(@exercise) %> |
  <%= link_to "Back to exercises", exercises_path %>

  <%= button_to "Destroy this exercise", @exercise, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice" style="color: green"><%= notice %></p>
    <p class="alert" style="color: red"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to "Create Excercise", new_exercise_path %>
      <%= link_to "Create Routine", new_routine_path %>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= button_to "Sign in", new_user_session_path, method: :get %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/routines/_form.html.erb
<%= form_with(model: routine) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.collection_check_boxes :exercise_ids, Exercise.all, :id, :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routines/_routine.html.erb
<div id="<%= dom_id routine %>">
</div>

app/views/routines/edit.html.erb
<h1>Editing routine</h1>

<%= render "form", routine: @routine %>

<br>

<div>
  <%= link_to "Show this routine", @routine %> |
  <%= link_to "Back to routines", routines_path %>
</div>

app/views/routines/index.html.erb
<h1>Routines</h1>

<div id="routines">
  <table>
    <thead>
      <tr>
        <th><strong>Name</strong></th>  
      </tr>
    </thead>
    <tbody>      
      <% @routines.each do |routine| %>
        <tr>
          <td><%= routine.name %></td>
          <td><%= link_to "show routine", routine %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New routine", new_routine_path %>  
</div>

app/views/routines/new.html.erb
<h1>New routine</h1>

<%= render "form", routine: @routine %>

<br>

<div>
  <%= link_to "Back to routines", routines_path %>
</div>

app/views/routines/show.html.erb
<div id="routine">
  <table>
    <thead>
      <tr>
        <th><strong>Exercise name</strong></th>
        <th><strong>Exercise description</strong></th>
        <th><strong>Exercise power level</strong></th>  
        <tr>
          <th colspan="3"><%= @routine.name %></th>
        </tr>
      </tr>
    </thead>
    <tbody>
      <% @routine.exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.name %></td>
          <td><%= exercise.description %></td>
          <td><%= exercise.power_level %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= link_to "Edit this routine", edit_routine_path(@routine) %> |
  <%= link_to "Back to routines", routines_path %>

  <%= button_to "Destroy this routine", @routine, method: :delete %>
</div>